name: Create preview

on:
  push:
    branches-ignore:
      - master

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name | sed -e 's/\//-/g' | tr '[:upper:]' '[:lower:]')}}
jobs:
  publish:
    name: Preview
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Test branch name
        run: echo ${{env.BRANCH_NAME}}
