name: Create preview

on:
  push:
    branches-ignore:
      - master

jobs:
  publish:
    name: Preview
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Echo branch name
        run: echo ${GITHUB_REF##*/}

      - name: Install Dependencies
        run: npm install

      - name: Install Netlify CLI
        run: npm install netlify-cli -g

      - name: Create Preview
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: netlify build --context deploy-preview --alias ${{ env.BRANCH_NAME }} && netlify deploy --dir=.next
