name: Create preview

on:
  push:
    branches-ignore:
      - master

jobs:
  publish:
    name: "Preview"
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master

      - uses: netlify/actions/cli@master
        with:
          args: netlify build --context production
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
