name: Test
on:
  push:
    branches-ignore:
      - master

jobs:
  publish:
    name: Test preview
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2

      - name: Test bash script
        env:
          BRANCH_NAME: ${{ (github.head_ref || github.ref_name) | sed -e 's/\//-/g'  }}
        run: echo ${{ env.BRANCH_NAME }}
